from __future__ import annotations

import pytest

from src.data.schemas import LocationRecord


@pytest.fixture
def sample_records() -> list[LocationRecord]:
    return [
        LocationRecord(
            id="russia_data.csv:2:alpha-air-base",
            source_file="russia_data.csv",
            country="Russia",
            location_category="Counterforce",
            dataset_type="military",
            name="Alpha Air Base",
            type="Air Base",
            latitude=55.0,
            longitude=37.0,
            region="Moscow Oblast",
            raw={"Name": "Alpha Air Base", "Oblast": "Moscow Oblast", "Type": "Air Base"},
        ),
        LocationRecord(
            id="russia_data.csv:3:bravo-defense",
            source_file="russia_data.csv",
            country="Russia",
            location_category="Counterforce",
            dataset_type="military",
            name="Bravo Defense Site",
            type="Air Defense",
            latitude=56.0,
            longitude=38.0,
            raw={"Name": "Bravo Defense Site", "Type": "Air Defense"},
        ),
        LocationRecord(
            id="china_data.csv:2:anqing-air-base",
            source_file="china_data.csv",
            country="China",
            location_category="Counterforce",
            dataset_type="military",
            name="Anqing Air Base",
            type="Air Base",
            latitude=30.58333,
            longitude=117.05,
            alternate_names="Anqing Tianzhushan Airport",
            iata="AQG",
            icao="ZSAQ",
            use="Dual",
            subordinate="ETCAF",
            tenants="28th Bomber Regiment",
            raw={
                "Name": "Anqing Air Base",
                "Alternate names": "Anqing Tianzhushan Airport",
                "IATA": "AQG",
                "ICAO": "ZSAQ",
                "Use": "Dual",
                "Subordinate": "ETCAF",
                "Tenants": "28th Bomber Regiment",
                "Type": "Air Base",
            },
        ),
        LocationRecord(
            id="metro_areas.csv:2:chongqing",
            source_file="metro_areas.csv",
            country="China",
            location_category="Countervalue",
            dataset_type="metro_area",
            name="Chongqing",
            type="Metro Area",
            latitude=29.55,
            longitude=106.5069,
            region="Chongqing",
            iso2="CN",
            population=32054159,
            population_proper=32054159,
            capital_status="admin",
            source_country_name="China",
            source_url="https://example.test/cn.csv",
            raw={
                "Country": "China",
                "ISO2": "CN",
                "Metro Area / City": "Chongqing",
                "Admin Region": "Chongqing",
                "Population": "32,054,159",
                "Population Proper": "32,054,159",
                "Capital Status": "admin",
                "Source Country Name": "China",
            },
        ),
        LocationRecord(
            id="metro_areas.csv:3:pyongyang",
            source_file="metro_areas.csv",
            country="North Korea",
            location_category="Countervalue",
            dataset_type="metro_area",
            name="Pyongyang",
            type="Metro Area",
            latitude=39.03,
            longitude=125.73,
            region="Pyongyang",
            iso2="KP",
            population=3222000,
            population_proper=3222000,
            capital_status="primary",
            source_country_name="North Korea",
            source_url="https://example.test/kp.csv",
            raw={
                "Country": "North Korea",
                "ISO2": "KP",
                "Metro Area / City": "Pyongyang",
                "Admin Region": "Pyongyang",
                "Population": "3,222,000",
                "Population Proper": "3,222,000",
                "Capital Status": "primary",
                "Source Country Name": "North Korea",
            },
        ),
        LocationRecord(
            id="iran_data.csv:2:mehrabad-international-airport",
            source_file="iran_data.csv",
            country="Iran",
            location_category="Counterforce",
            dataset_type="military",
            name="Mehrabad International Airport",
            type="Air Base",
            latitude=35.6886,
            longitude=51.3128,
            notes="F-14s located at this base",
            raw={
                "Country": "Iran",
                "Type": "Air Base",
                "Name": "Mehrabad International Airport",
                "Latitude": "35.6886",
                "Longitude": "51.3128",
                "Notes": "F-14s located at this base",
            },
        ),
        LocationRecord(
            id="dprk_data.csv:2:sakkanmol-missile-operating-base",
            source_file="dprk_data.csv",
            country="DPRK",
            location_category="Counterforce",
            dataset_type="military",
            name="Sakkanmol Missile Operating Base",
            type="Missile operating base",
            latitude=38.584698,
            longitude=126.107945,
            category_source="Rocket launch site",
            notes="Short-range ballistic missiles in North Hwanghae Province",
            raw={
                "Category Source": "Rocket launch site",
                "Country": "DPRK",
                "Name": "Sakkanmol Missile Operating Base",
                "Type": "Missile operating base",
                "Latitude": "38.584698",
                "Longitude": "126.107945",
                "Notes": "Short-range ballistic missiles in North Hwanghae Province",
            },
        ),
    ]
