from __future__ import annotations

import pytest

from src.data.schemas import LocationRecord


@pytest.fixture
def sample_records() -> list[LocationRecord]:
    return [
        LocationRecord(
            id="russia_data.csv:2:alpha-air-base",
            source_file="russia_data.csv",
            map_layer="adversary_military",
            country="Russia",
            operator_country="Russia",
            location_category="Counterforce",
            dataset_type="military",
            name="Alpha Air Base",
            type="Air Base",
            latitude=55.0,
            longitude=37.0,
            region="Moscow Oblast",
            raw={"Name": "Alpha Air Base", "Oblast": "Moscow Oblast", "Type": "Air Base"},
        ),
        LocationRecord(
            id="russia_data.csv:3:bravo-defense",
            source_file="russia_data.csv",
            map_layer="adversary_military",
            country="Russia",
            operator_country="Russia",
            location_category="Counterforce",
            dataset_type="military",
            name="Bravo Defense Site",
            type="Air Defense",
            latitude=56.0,
            longitude=38.0,
            raw={"Name": "Bravo Defense Site", "Type": "Air Defense"},
        ),
        LocationRecord(
            id="china_data.csv:2:anqing-air-base",
            source_file="china_data.csv",
            map_layer="adversary_military",
            country="China",
            operator_country="China",
            location_category="Counterforce",
            dataset_type="military",
            name="Anqing Air Base",
            type="Air Base",
            latitude=30.58333,
            longitude=117.05,
            alternate_names="Anqing Tianzhushan Airport",
            iata="AQG",
            icao="ZSAQ",
            use="Dual",
            subordinate="ETCAF",
            tenants="28th Bomber Regiment",
            raw={
                "Name": "Anqing Air Base",
                "Alternate names": "Anqing Tianzhushan Airport",
                "IATA": "AQG",
                "ICAO": "ZSAQ",
                "Use": "Dual",
                "Subordinate": "ETCAF",
                "Tenants": "28th Bomber Regiment",
                "Type": "Air Base",
            },
        ),
        LocationRecord(
            id="global_cities_metros_100k.csv:G000003:chongqing",
            source_file="global_cities_metros_100k.csv",
            map_layer="global_metros",
            country="China",
            location_category="Non-Military",
            dataset_type="metro_area",
            name="Chongqing",
            type="Metro Area",
            latitude=29.55,
            longitude=106.5069,
            region="Chongqing",
            admin_area="Chongqing",
            iso2="CN",
            iso3="CHN",
            timezone="Asia/Shanghai",
            population=32054159,
            population_source="Bamwor",
            population_bamwor=32054159,
            population_simplemaps=32000000,
            population_starting_list=32054159,
            population_size_class="10M+",
            capital_classification="admin",
            country_gdp_per_capita_usd=12500,
            country_gdp_ppp_usd=35000000000000,
            primary_source="Bamwor",
            openstreetmap_url="https://www.openstreetmap.org/search?query=Chongqing",
            wikipedia_search_url="https://en.wikipedia.org/w/index.php?search=Chongqing",
            image_research_url="https://example.test/images?q=Chongqing",
            starting_list_included=True,
            raw={
                "Country": "China",
                "ISO2": "CN",
                "ISO3": "CHN",
                "Location_Name": "Chongqing",
                "Admin1_Name": "Chongqing",
                "Population": "32,054,159",
                "Population_Source": "Bamwor",
            },
        ),
        LocationRecord(
            id="global_cities_metros_100k.csv:G000300:pyongyang",
            source_file="global_cities_metros_100k.csv",
            map_layer="global_metros",
            country="North Korea",
            location_category="Non-Military",
            dataset_type="metro_area",
            name="Pyongyang",
            type="Metro Area",
            latitude=39.03,
            longitude=125.73,
            region="Pyongyang",
            admin_area="Pyongyang",
            iso2="KP",
            iso3="PRK",
            timezone="Asia/Pyongyang",
            population=3222000,
            population_source="SimpleMaps",
            population_bamwor=3222000,
            population_simplemaps=3222000,
            population_size_class="1M-5M",
            capital_classification="primary",
            primary_source="SimpleMaps",
            raw={
                "Country": "North Korea",
                "ISO2": "KP",
                "ISO3": "PRK",
                "Location_Name": "Pyongyang",
                "Admin1_Name": "Pyongyang",
                "Population": "3,222,000",
                "Population_Source": "SimpleMaps",
            },
        ),
        LocationRecord(
            id="iran_data.csv:2:mehrabad-international-airport",
            source_file="iran_data.csv",
            map_layer="adversary_military",
            country="Iran",
            operator_country="Iran",
            location_category="Counterforce",
            dataset_type="military",
            name="Mehrabad International Airport",
            type="Air Base",
            latitude=35.6886,
            longitude=51.3128,
            notes="F-14s located at this base",
            raw={
                "Country": "Iran",
                "Type": "Air Base",
                "Name": "Mehrabad International Airport",
                "Latitude": "35.6886",
                "Longitude": "51.3128",
                "Notes": "F-14s located at this base",
            },
        ),
        LocationRecord(
            id="dprk_data.csv:2:sakkanmol-missile-operating-base",
            source_file="dprk_data.csv",
            map_layer="adversary_military",
            country="DPRK",
            operator_country="DPRK",
            location_category="Counterforce",
            dataset_type="military",
            name="Sakkanmol Missile Operating Base",
            type="Missile operating base",
            latitude=38.584698,
            longitude=126.107945,
            category_source="Rocket launch site",
            notes="Short-range ballistic missiles in North Hwanghae Province",
            raw={
                "Category Source": "Rocket launch site",
                "Country": "DPRK",
                "Name": "Sakkanmol Missile Operating Base",
                "Type": "Missile operating base",
                "Latitude": "38.584698",
                "Longitude": "126.107945",
                "Notes": "Short-range ballistic missiles in North Hwanghae Province",
            },
        ),
        LocationRecord(
            id="us_military_sites.csv:US0001:ramstein-air-base",
            source_file="us_military_sites.csv",
            map_layer="us_military",
            country="Germany",
            operator_country="United States",
            location_category="Military Site",
            dataset_type="military",
            name="Ramstein Air Base",
            type="Air Force",
            latitude=49.4369,
            longitude=7.6003,
            admin_area="Rhineland-Palatinate",
            component="Active",
            service_branch="Air Force",
            component_status="Active",
            location_class="Installation",
            geographic_scope="Overseas",
            nearest_city="Ramstein-Miesenbach",
            coordinate_quality="Representative point",
            buildings_owned=100,
            buildings_owned_sqft=1234567,
            acres_owned=1200,
            total_acres=1400,
            plant_replacement_value_m=2500,
            coordinate_source_url="https://example.test/coordinate",
            dataset_source_url="https://example.test/dataset",
            notes="Public representative point.",
            raw={
                "Record_ID": "US0001",
                "Site": "Ramstein Air Base",
                "Host_Country": "Germany",
                "Service_Branch": "Air Force",
                "Coordinate_Quality": "Representative point",
                "Notes": "Public representative point.",
            },
        ),
    ]
